#+STARTUP: indent
* imgui_multiplotlines
ImGui::MultiPlotLines() is a nearly drop-in alternative to
ImGui::PlotLines() that allows drawing multiple channels
simultaneously and adds some nice extra features on top.
** TODO Screenshot/GIF
* Features
Draw N channels simultaneously in separate Plot and Legend views.

Channels:
- Have a user-defined name and colour
- Can be shown/hidden interactively
- Can be highlighted and selected

Plot View:
- Draws N channel curves simultaneously in their respective colours
- Channel curves can be hovered and clicked for custom interaction
- Can filter curves to smoothen noisy input data

Legend View:
- Shows channel names and status (visible,hovered,selected...)
- Channel names can be hovered and clicked for custom interaction
- Can be shown/hidden interactively
* TODO GIF
* Guide
See ImGui::MultiPlotLines_Demo() for example code showing how to use most available features.

Basic usage is similar to ImGui::PlotLines(), and only requires the following changes:
- Providing a get_value() function pointer that accepts and additional channel_idx parameter
- Providing the number of channels

Advanced usage requires passing an non-null ImGui::MultiPlotLines_Params
struct pointer, that can be persistent or non-persistent.

Non-persistent params allow fine-tuning the Plot/Legend appearance and
enable some minimal interaction:
- Enable/Disable per-channel visibility
- Enable Legend and other UI elements
- Filter channel data
- RW_HoveredChannelIdx and RW_SelectedChannelIdx can be queried after
  drawing, but will be reset on next call

Persistent params allow tracking and interactive modification of
read-write parameters (prefixed by RW_):
- Toggle channel visibility
- Toggle channel selection
- Hide/Show Legend interactively
- Highlight Plot channels when hovering over Legend entries (with
  non-persistent params, hovered Plot channels will be highlghted in
  Legend, but not the other way around)

** Limitations:
- All plots use the same vertical range
- All channels are assumed to have the same number of samples (horizontal range)
- No support for values_offset or overlay_text, available in ImGui::PlotLines()

User-defined get_value() functions can easily work around these, but
I've tried to keep the API and default behaviour as simple as possible.
** Advanced
*** Channel colours
The default palette is good enough, but users can provide a
get_channel_color() function to customize these at will
*** MouseClickActions

* Installation
Install boost... :scared: no, really, just copy imgui_multiplotlines.h/cpp to
your project folders or your ImGui installation and you're good to go :rocket:

NOTE: Requires C++11 due to some lightweight of non-capturing lambdas
and inline struct initialization, could be implemented without but
code would be a lot uglier.
* Potential improvements
- Legend could be optionally placed beside/above Plot, instead of below
- Plot axis labels and ticks markcs
- Plot navigation with zoom, pan, selection
- Alternative Legend view that shows channels as a collapsable
  hierarchy instead of a flat column-based layout
- Generic MouseClickAction that opens a context menu with all available actions
- User-defined MouseClickAction that calls a user-provided function pointer
* See also
- [[https://github.com/ocornut/imgui/][Dear ImGui]]
- ImPlot: Fully featured plotting library: https://github.com/epezent/implot
- imgui-plot: An improved plot widget aimed at displaying audio data https://github.com/soulthreads/imgui-plot
